development: &default
  adapter:  postgresql
  host:     db
  encoding: unicode
  database: boxenite_development
  pool:     5
  username: postgres
  password:
  template: template0

development:
  <<: *default
  database: boxenite_development

test:
  <<: *default
  database: boxenite_test

production:
  <<: *default
  database: boxenite_production
